# Generated by Django 3.1.4 on 2021-03-22 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job_Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=10000)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=500)),
                ('work_level', models.CharField(max_length=100)),
                ('is_experience', models.BooleanField()),
                ('quota', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Company_Profile',
            fields=[
                ('user_profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.user_profile')),
                ('company_name', models.CharField(max_length=100)),
                ('tax_id', models.IntegerField(max_length=60)),
                ('website', models.CharField(max_length=100)),
                ('foundation_year', models.DateField()),
            ],
            bases=('website.user_profile',),
        ),
        migrations.CreateModel(
            name='Job_Seeker_Profile',
            fields=[
                ('user_profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='website.user_profile')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('carrier_list', models.CharField(max_length=2000)),
                ('portfolio_link', models.CharField(max_length=100)),
            ],
            bases=('website.user_profile',),
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('almater', models.CharField(max_length=100)),
                ('graduation_date', models.DateField()),
                ('internships', models.CharField(max_length=2000)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=20)),
                ('experience_field', models.CharField(max_length=500)),
                ('extras', models.CharField(max_length=1000)),
                ('interests', models.CharField(max_length=1000)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_owner', to='website.job_seeker_profile')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_job_offer', to='website.job_offer')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_applicant', to='website.job_seeker_profile')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_employer', to='website.company_profile')),
            ],
        ),
    ]
