# Generated by Django 3.1.4 on 2021-03-28 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20210322_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_profile',
            name='foundation_year',
            field=models.IntegerField(),
        ),
    ]
