# Generated by Django 3.1.4 on 2021-04-15 18:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210328_2008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_offer',
            name='end_date',
        ),
        migrations.AddField(
            model_name='company_profile',
            name='image',
            field=models.ImageField(blank=True, default='company_image/default', null=True, upload_to='company_image'),
        ),
        migrations.AddField(
            model_name='job_offer',
            name='education',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='job_offer',
            name='post_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job_offer',
            name='required_skills',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='job_offer',
            name='salary',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='job_offer',
            name='is_experience',
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name='job_offer',
            name='quota',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='job_offer',
            name='start_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='job_offer',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='job_offer',
            name='work_level',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
