# Generated by Django 3.1.7 on 2021-04-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20210328_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_profile',
            name='image',
            field=models.ImageField(blank=True, default='company_image/default', null=True, upload_to='company_image'),
        ),
    ]
