# Generated by Django 3.1.4 on 2021-04-15 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20210415_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_offer',
            name='company',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='job_offer_company', to='website.company_profile'),
            preserve_default=False,
        ),
    ]
