# Generated by Django 3.1.4 on 2021-04-15 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_job_offer_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_offer',
            name='quota',
        ),
    ]
