# Generated by Django 3.1.4 on 2021-04-18 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_company_profile_image'),
        ('website', '0006_remove_job_offer_quota'),
    ]

    operations = [
    ]
