# Generated by Django 3.1.7 on 2021-04-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_merge_20210418_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_seeker_profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='job_seeker_profile',
            name='image',
            field=models.ImageField(blank=True, default='job_seeker_image/default', null=True, upload_to='job_seeker_image'),
        ),
    ]
