# Generated by Django 3.1.7 on 2021-04-19 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_cv_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='experience_field',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='cv',
            name='extras',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='cv',
            name='interests',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='cv',
            name='internships',
            field=models.TextField(max_length=2000),
        ),
    ]
