# Generated by Django 3.1.7 on 2021-04-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20210419_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='address',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cv',
            name='cv_img',
            field=models.ImageField(blank=True, default='cv_img/default', null=True, upload_to='cv_image'),
        ),
        migrations.AddField(
            model_name='cv',
            name='licences_status',
            field=models.IntegerField(choices=[(1, 'Have'), (0, 'Have Not')], default=1),
        ),
        migrations.AddField(
            model_name='cv',
            name='military_status',
            field=models.IntegerField(choices=[(1, 'Done'), (0, 'Not Done')], default=1),
        ),
    ]
