# Generated by Django 3.1.7 on 2021-04-20 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20210419_2145'),
        ('website', '0008_auto_20210418_1742'),
    ]

    operations = [
    ]
