# Generated by Django 3.1.4 on 2021-04-21 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_auto_20210419_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_offer',
            name='is_experience',
        ),
        migrations.AddField(
            model_name='job_offer',
            name='categories',
            field=models.CharField(choices=[('design', 'Design & Creative'), ('design_development', 'Design & Development'), ('sales_marketing', 'Sales & Marketing'), ('mobile_app', 'Mobile Application'), ('construction', 'Construction'), ('it', 'Information Technology'), ('real_estate', 'Real Estate'), ('content_writer', 'Content Writer')], default='design', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job_offer',
            name='experience',
            field=models.CharField(blank=True, choices=[('0_years', 'No experience'), ('1_2_years', '1-2 years'), ('2_3_years', '2-3 years'), ('3_6_years', '3-6 years'), ('6_more_years', '6-more years')], max_length=100),
        ),
        migrations.AlterField(
            model_name='job_offer',
            name='location',
            field=models.CharField(choices=[('istanbul', 'Istanbul'), ('ankara', 'Ankara'), ('izmir', 'Izmir'), ('bursa', 'Bursa')], max_length=500),
        ),
        migrations.AlterField(
            model_name='job_offer',
            name='type',
            field=models.CharField(blank=True, choices=[('full_time', 'Full Time'), ('part_time', 'Part Time'), ('intern', 'Internship'), ('remote', 'Remote')], max_length=25),
        ),
    ]
