# Generated by Django 3.1.4 on 2021-04-25 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_auto_20210425_1528'),
        ('website', '0011_merge_20210420_0101'),
        ('website', '0011_auto_20210421_2353'),
    ]

    operations = [
    ]
