# Generated by Django 3.1.4 on 2021-04-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_auto_20210426_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job_offer',
            name='location',
            field=models.CharField(choices=[('istanbul', 'Istanbul'), ('ankara', 'Ankara'), ('izmir', 'Izmir'), ('bursa', 'Bursa')], max_length=500),
        ),
    ]
